[main]
font = JetBrainsMono Nerd Font:size=13
dpi-aware = no
prompt = "   "
icon-theme = BeautyLine
icons-enabled = yes
show-actions = no
terminal = kitty

width = 45
lines = 12
horizontal-pad = 16
vertical-pad = 12
inner-pad = 8
line-height = 22

# Positioning
anchor = top-left
x-margin = 6
y-margin = 6
layer = overlay

[colors]
background = 1c0e28f5
text = e8e0f0ff
match = f5c2e7ff
selection = b48cdcee
selection-text = 1c0e28ff
selection-match = f5c2e7ff
border = b48cdc99

[border]
width = 2
radius = 12