-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:ASUSTek COMPUTER INC VG278 L4LMQS098839",
  mode = "1920x1080@164.92",
  position = "0x600",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company LS24F32xG HNCL303755",
  mode = "1920x1080@60.00",
  position = "1920x0",
  scale = 1,
  transform = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:ASUSTek COMPUTER INC VG278 L4LMQS098839", default = true, persistent = true })
