splash = false
ipc = on

wallpaper {
    monitor = DP-1
    path = /home/ryan/Pictures/backgrounds/Sus/sit-purple.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/ryan/Pictures/backgrounds/purple.png
    fit_mode = fill
}

# Fallback for any other monitor
wallpaper {
    monitor =
    path = /home/ryan/Pictures/backgrounds/Sus/sit-purple.png
    fit_mode = cover
}