general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms("on")'
}

# Dim the screen after 5 minutes
#listener {
#    timeout = 300
#    on-timeout = ddcutil --display 1 setvcp 10 10; ddcutil --display 2 setvcp 10 10
#    on-resume = ddcutil --display 1 setvcp 10 25; ddcutil --display 2 setvcp 10 60
#}

# Fully turn off the display after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")' 
}

# Lock session after 8 minutes
listener {
    timeout = 480
    on-timeout = loginctl lock-session
}

# Optional: suspend the system after 20 minutes idle
# listener {
#     timeout = 1200
#     on-timeout = systemctl suspend
# }